### ISSUE TITLE
Random crash / Mod incompatibility - Latest version 1.20.2

### ISSUE THREAD

**Issue by sternschnaube** [jj21asd/BetterSmithingUI#2] opened 2023-12-27 21:58 UTC
When I try to open the GUI:

Unreported exception thrown!
java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4895 failed
	at net.minecraft.class_3929.<clinit>(class_3929.java:103)
	at net.minecraft.class_634.method_17587(class_634.java:1150)
	at net.minecraft.class_3944.method_17591(class_3944.java:37)
	at net.minecraft.class_3944.method_11054(class_3944.java:11)
	at net.minecraft.class_2600.method_11072(class_2600.java:23)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.mixinextras$bridge$method_18859$5(class_4093.java)
	at net.minecraft.class_4093.wrapOperation$dhk000$carpet-tis-addition$yeetUpdateSuppressionCrash_implForThreadExecutorTaskExecuting(class_4093.java:570)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1231)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4895 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:75)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 21 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector renderBg(Lnet/minecraft/class_8064;Lnet/minecraft/class_1703;Lnet/minecraft/class_332;FII)V in mixins.brb-common.json:SmithingScreenMixin from mod brb failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap brb-common-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 25 more

**Comment by ffuentesm** [comment] 2023-12-29 05:06
Saem, for some reason I am also getting a crash on start for some reason. If I disable the mod things work.
I am on 1.20.1
https://mclo.gs/J49MkRd

**Comment by jjblock21** [comment] 2023-12-29 22:38
Ok, thanks for reporting this. I will investigate and try to get a fix out by tomorrow.

**Comment by sternschnaube** [comment] 2023-12-29 23:05
Awesome 😊

**Comment by jjblock21** [comment] 2024-01-03 22:23
Ok didn't get it done by whenever tomorrow was but be assured I am working on it

**Comment by jjblock21** [comment] 2024-01-03 22:37
These two are two very different cases though since they are concerning different versions of the mod so I will examine them separately. I will close this issue when both are fixed.

**Comment by jjblock21** [comment] 2024-01-04 17:19
> When I try to open the GUI:
> 
> Unreported exception thrown! java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_4895 failed at net.minecraft.class_3929.(class_3929.java:103) at...

I've tried to recreate this error on the newest version on Curseforge and had no success. Can you verify if you are really using the newest version?

**Comment by sternschnaube** [comment] 2024-01-04 17:37
I highly assume it's a mod compatibility error. But now you can't make a use of my mod list, since it's too big.

If I find time I could investigate more into it and spot which mods causing this issue.

**Comment by jjblock21** [comment] 2024-01-04 17:43
> I highly assume it's a mod compatibility error. But now you can't make a use of my mod list, since it's too big.
> 
> If I find time I could investigate more into it and spot which mod is creating this issue.

Can you upload the full crash log so I can investigate what specifically might be failing? If you are using fabric it would also be great to install the mixintrace mod beforehand to give me some extra information on what might be goign wrong.

**Comment by sternschnaube** [comment] 2024-01-04 17:46
I will do that later 😊

**Comment by jjblock21** [comment] 2024-01-04 18:01
> Saem, for some reason I am also getting a crash on start for some reason. If I disable the mod things work. I am on 1.20.1 https://mclo.gs/J49MkRd

This is probably a mod compatibility problem aswell. From the crash log it looks like another mod is messing with the dynamic slot icons in the smithing menu so BetterSmithingTable fails when trying to prevent them from rendering. If you are using a publically available modpack you can share it with me so i can attempt to debug the issue with your configuration.

**Comment by ffuentesm** [comment] 2024-01-04 18:18
I think it might be one of these: 
![image](https://github.com/jjblock21/BetterSmithingTable/assets/44974827/f0d18e0d-aa6b-4164-a6ec-51b37cacb60e)

Not using a public modpack, just some mods that I like.

**Comment by jjblock21** [comment] 2024-01-04 22:06
> I think it might be one of these: [...]
> 
> Not using a public modpack, just some mods that I like. I removed half of the mods I play with, mostly major mods, and this crash still happens when better smithtable is installed. [crash-2024-01-04_13.15.06-fml.txt](https://github.com/jjblock21/BetterSmithingTable/files/13834177/crash-2024-01-04_13.15.06-fml.txt) the crash also has the mods installed
> 
> > [...]

I can see an error caused by the mod in the crash report but it's weirdly merged with fault in the Corpse mod. This might be because the two are incompatible, but it could also just be some weirdness in the way the error is logged. Try removing the Corpse mod and opening the smithing interface again.
If the issue still persists please upload the crash report again so I check if anything changed.

**Comment by jjblock21** [comment] 2024-01-04 22:11
Actually looking at the code there is no reason this mod should mess with BetterSmithingTable, but please still try without it.

**Comment by ffuentesm** [comment] 2024-01-05 00:57
> Actually looking at the code there is no reason this mod should mess with BetterSmithingTable, but please still try without it.

 I also tested other UI mods, and both Better Recipe Book, and Recipe Book is Pain are causing the problem.

**Comment by sternschnaube** [comment] 2024-01-05 03:38
Thanks @ffuentesm, I use Better Recipe Book too, maybe that's the issue mod. I will investigate soon into it.

**Comment by sternschnaube** [comment] 2024-01-05 08:38
I can confirm that Better Recipe Book is the problem here.

I am using version: brb-1.10.0+1.20.2

**Comment by jjblock21** [comment] 2024-01-05 20:31
Ok, I assume this issue can be closed now. I will look at Better Recipe Book and check if I can make the two compatible.

**Comment by jjblock21** [comment] 2024-01-05 20:36
Ah yes, the incompatibiliy is very obvious. The same method call is being redirected once in Better Recipe Book and once in Better Smithing Table. The fix should not be too hard though.

**Comment by jjblock21** [comment] 2024-01-05 20:36
I will close this issue after the fix is ready.

**Comment by sternschnaube** [comment] 2024-01-06 02:16
Thank you!! 🥳

**Comment by jjblock21** [comment] 2024-01-06 18:18
Ok, the fix is in the new version for 1.20.2 - 1.20.4. The fix for 1.20.1 will take a little more time as I need to repeat the changes for the version for 1.20 - 1.20.1.

**Comment by sternschnaube** [comment] 2024-01-06 20:00
Thank you, I will update to that version soon.

**Comment by jj21asd** [comment] 2024-12-07 23:51
2.0.0 should fix this for 1.20.1 as well

**Closed by jj21asd** 2024-12-07 23:51 UTC
Labels: bug
